---
name: Release announcement
on:
  release:
    types: [published]

jobs:
  notify:
    name: Notify new release
    runs-on: ubuntu-latest
    if: github.event.release.name != ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notifiy dedicated teams channel
        uses: simbo/msteams-message-card-action@v1.4.3
        with:
          webhook-url: ${{ secrets.TEAMS_SYS_WEBHOOK_TEST_URI }}
          title: "New Release for ${{ github.repository }}"
          message: "Release ${{ github.event.release.name }} on repository ${{ github.repository }} has just been published!"
          color: "ff6e00"
          buttons: |
            Open release notes in GitHub https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.name }}
