---
name: Release announcement
on:
  release:
    types: [published]

jobs:
  notify:
    name: Notify new release
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Teams
        run: |
          if [ "${{ github.event.release.name }}" != '' ]; then
            curl -X POST "${{ secrets.TEAMS_SYS_WEBHOOK_TEST_URI }}" \
            --data '{"@context":"https://schema.org/extensions","@type":"MessageCard","themeColor":"ff6e00","title":"Release ${{ github.event.release.name }} on repository ${{ github.repository }} has just been published!","text":"${{ github.event.release.body }}"}'
          fi
        shell: bash
